readme: Include a FAQ & Cleanup
Nilsen84/lcqt2 pull request #6
Opened 2023-08-03 18:30 UTC by uchks

Cleans up README.
Adds a FAQ for users.
Includes Windows Portable download link.
DDLs: `windows-portable.zip`, `macos/linux-portable.tar.gz` (*due to versioning, Windows Setup isn't a ddl.)

2023-08-03 19:29 UTC, Nilsen84 requested changes
LGTM, just one small correction

2023-08-03 19:29 UTC, Nilsen84 commented on README.md
> +  - Debug: Enables "Staff" Mods (Currently only X-Ray).
It also enables two other mods meant for internal use: Panorama Maker & GeckoLib Debug Mod

2023-08-04 18:35 UTC, uchks commented on README.md
> +  - Debug: Enables "Staff" Mods (Currently only X-Ray).
Just noted they were for internal use only.

2023-08-05 01:00 UTC, Nilsen84 approved these changes

2023-08-05 01:04 UTC, merged